apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverycontext
  labels:
    app: deliverycontext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliverycontext
  template:
    metadata:
      labels:
        app: deliverycontext
    spec:
      containers:
        - name: deliverycontext
          image: username/deliverycontext:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-profile
              mountPath: /tmp/config
          volumes:
            - name: config-profile
              configMap:
                name: hello-cm
